<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-23T12:33:54 IST" name="Suite" finished-at="2023-12-23T12:34:22 IST" duration-ms="28136">
    <groups>
    </groups>
    <test started-at="2023-12-23T12:33:54 IST" name="End to end Framework Test" finished-at="2023-12-23T12:34:22 IST" duration-ms="28136">
      <class name="org.Yosa.Appium_gsm.Yosa_Apk_tc_1">
        <test-method is-config="true" signature="CofigureAppium()[pri:0, instance:org.Yosa.Appium_gsm.Yosa_Apk_tc_1@626abbd0]" started-at="2023-12-23T12:33:54 IST" name="CofigureAppium" finished-at="2023-12-23T12:34:07 IST" duration-ms="13021" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CofigureAppium -->
        <test-method signature="SignIn()[pri:0, instance:org.Yosa.Appium_gsm.Yosa_Apk_tc_1@626abbd0]" started-at="2023-12-23T12:34:07 IST" name="SignIn" finished-at="2023-12-23T12:34:16 IST" duration-ms="9306" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<> but was:<Please enter name>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<> but was:<Please enter name>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at org.Yosa.Appium_gsm.Yosa_Apk_tc_1.SignIn(Yosa_Apk_tc_1.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignIn -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.Yosa.Appium_gsm.Yosa_Apk_tc_1@626abbd0]" started-at="2023-12-23T12:34:17 IST" name="tearDown" finished-at="2023-12-23T12:34:22 IST" duration-ms="5312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.Yosa.Appium_gsm.Yosa_Apk_tc_1 -->
    </test> <!-- End to end Framework Test -->
  </suite> <!-- Suite -->
</testng-results>
